name: buildx
on: ['push']
jobs:
  build:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: rustup default ${{ matrix.channel }}
      - uses: rust-lang/simpleinfra/github-actions/simple-ci@master
    strategy:
      matrix:
        os: ['ubuntu-latest']
        channel: ['stable']
        run: |
          export COMPOSE_DOCKER_CLI_BUILD=1
          cargo build --release --features final
 
      - uses: docker/setup-buildx-action@v1.1.2
        id: buildx
        with:
          install: true
          
      - name:  BuildX
        run: |
          export COMPOSE_DOCKER_CLI_BUILD=1
          export DOCKER_BUILDKIT=1
          build -f scripts/docker/hub/Dockerfile --tag manifoldfinance/openethereum-instantseal .
